apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: zqetnsuns-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-qe-jsmid/zqetnsuns-java-quarkus-gitops